---
label: project
hide_body: true
fields:
- type: text
  name: layout
  label: layout
  default: project
  config:
    required: true
  hidden: true
- type: image_gallery
  name: images
  label: images
- name: categories
  type: tag_list
  default: []
  label: categories
  description: project categories
- type: text
  name: title
  label: title
- type: text
  name: description
  label: description
- type: text
  name: authors
  label: authors
  default: Markéta a Petr Veličkovi
- name: year
  type: datetime
  label: year
  description: ''
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
- type: text
  name: location
  label: location
- type: text
  name: investor
  label: investor
- type: text
  name: visualization
  label: visualization
- type: text
  name: size
  label: size
- type: text
  name: price
  label: price
- type: text
  name: slug
  label: slug
  hidden: true
pages:
- _projects/název-projektu-11-1.md
- _projects/název-projektu-12.md
- _projects/název-projektu-11.md
- _projects/project-1.md
